---
title: "T3"
author: "Yamil"
date: "10/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problema 1

```{r}
Harry = -10:27
Harry
Harry[7]
```


# Problema 2

```{r}
s = 100* 2 ^ (0:200)-7* 3^(0:200)
max(s)
```

# Problema 3

```{r}
s = 0:40
x = 3*5^s-1
w = x[x>3.5]
w
```


#Problema 4

```{r}
com = function(x){c( round(Re(x),1),  round(Im(x),1),  round(Mod(x),1),  round(Arg(x),1),  round(Conj(x),1)  ) }

com(5.25+8.84i)

```

#Problema 5
```{r}
chicharronera = function(a,b,c){
  c((-b+sqrt(b*b-4*a*c))/(2*a),(-b-sqrt(b*b-4*a*c))/(2*a))
}

chicharronera(3,3,-7)
```

# Problema 6
```{r}
vec = c(0,9,98,2,6,7,5,19,88,20,16,0)
vec[vec == 9 | vec == 19 | vec == 20 | vec == 16]
vec[c(2,8,10,11)]
vec[-c(1,3:7,9,12)]

which(vec%%2==0)
which(!vec%%2==0 & vec>20)
which(vec == max(vec))
which(vec == min(vec))
```
 # Problema 7
```{r}
A = matrix(1:4, nrow = 2)
(A%*%(A+A)%*%A)[2,2]
```
# Problema 8
```{r}
B = matrix(c(2,0,0,4,0,-2,-6,3,5), nrow = 3)
eigen(B)$values
```

# Problema 9
```{r}
C = matrix(c(-48,-134, -194,  35,95, 133, -12, -32, -44), nrow = 3)
round(eigen(C)$values, 3)
```
# Problema 10
```{r}
D = matrix(c(-2,-3,-9,-18, -8,-6,-22, -44, -2,-1, -3,-8, 3, 2,7, 15),nrow = 4)
qr(D)$rank
```


































